---

apiVersion: skaffold/v2beta2
kind: Config

build:
  local:
    useBuildkit: true

profiles:
  - name: dev-source
    activation:
      - command: dev
    build:
      artifacts:
        - image: gopg
          sync:
            infer:
              - "**/*.go"
          docker:
            target: dev-source

  - name: debug
    activation:
      - command: debug
    build:
      artifacts:
        - image: gopg
          sync:
            infer:
              - "**/*.go"
          docker:
            target: debug

  - name: run
    activation:
      - command: run
    build:
      artifacts:
        - image: gopg
          docker:
            target: prod
