version: '2'

tasks:
  build-darwin:
    cmds:
      - GOOS=darwin GOARCH=amd64 go build -ldflags="-w -s" -o main-darwin.exe .
    desc: Builds an OSX executable

  build-linux:
    cmds:
      - GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o main-linux.exe .
    desc: Builds a Linux executable

  build-windows:
    cmds:
      - GOOS=windows GOARCH=amd64 go build -ldflags="-w -s" -o main-windows.exe .
    desc: Builds a Windows executable

  dev:
    cmds:
      - air
    desc: Runs the code and watches for changes (air)
    preconditions:
      - sh: "test ! -d out"
        msg: "Already running (found out)"
      - sh: "type air"
        msg: "https://github.com/cosmtrek/air#Installation"

  lint:
    cmds:
      - revive -config revive.toml -exclude=vendor/... ./...
    desc: Runs the linter (revive)
    preconditions:
      - sh: "type revive"
        msg: "https://github.com/mgechev/revive#installation"


