---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gopg-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gopg-app
  template:
    metadata:
      labels:
        app: gopg-app
    spec:
      containers:
        - name: gopg-app
          image: gopg
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
